// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vectors.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_vectors_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_vectors_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3009000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3009001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_vectors_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_vectors_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_vectors_2eproto;
class Proto3Data;
class Proto3DataDefaultTypeInternal;
extern Proto3DataDefaultTypeInternal _Proto3Data_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Proto3Data* Arena::CreateMaybeMessage<::Proto3Data>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Proto3Data :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Proto3Data) */ {
 public:
  Proto3Data();
  virtual ~Proto3Data();

  Proto3Data(const Proto3Data& from);
  Proto3Data(Proto3Data&& from) noexcept
    : Proto3Data() {
    *this = ::std::move(from);
  }

  inline Proto3Data& operator=(const Proto3Data& from) {
    CopyFrom(from);
    return *this;
  }
  inline Proto3Data& operator=(Proto3Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Proto3Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Proto3Data* internal_default_instance() {
    return reinterpret_cast<const Proto3Data*>(
               &_Proto3Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Proto3Data& a, Proto3Data& b) {
    a.Swap(&b);
  }
  inline void Swap(Proto3Data* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Proto3Data* New() const final {
    return CreateMaybeMessage<Proto3Data>(nullptr);
  }

  Proto3Data* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Proto3Data>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Proto3Data& from);
  void MergeFrom(const Proto3Data& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  #else
  bool MergePartialFromCodedStream(
      ::PROTOBUF_NAMESPACE_ID::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::PROTOBUF_NAMESPACE_ID::io::CodedOutputStream* output) const final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Proto3Data* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Proto3Data";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_vectors_2eproto);
    return ::descriptor_table_vectors_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVec1FieldNumber = 1,
    kVec2FieldNumber = 2,
  };
  // repeated uint64 Vec1 = 1;
  int vec1_size() const;
  void clear_vec1();
  ::PROTOBUF_NAMESPACE_ID::uint64 vec1(int index) const;
  void set_vec1(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_vec1(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      vec1() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_vec1();

  // repeated uint64 Vec2 = 2;
  int vec2_size() const;
  void clear_vec2();
  ::PROTOBUF_NAMESPACE_ID::uint64 vec2(int index) const;
  void set_vec2(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value);
  void add_vec2(::PROTOBUF_NAMESPACE_ID::uint64 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
      vec2() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
      mutable_vec2();

  // @@protoc_insertion_point(class_scope:Proto3Data)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > vec1_;
  mutable std::atomic<int> _vec1_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 > vec2_;
  mutable std::atomic<int> _vec2_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_vectors_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Proto3Data

// repeated uint64 Vec1 = 1;
inline int Proto3Data::vec1_size() const {
  return vec1_.size();
}
inline void Proto3Data::clear_vec1() {
  vec1_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Proto3Data::vec1(int index) const {
  // @@protoc_insertion_point(field_get:Proto3Data.Vec1)
  return vec1_.Get(index);
}
inline void Proto3Data::set_vec1(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  vec1_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto3Data.Vec1)
}
inline void Proto3Data::add_vec1(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  vec1_.Add(value);
  // @@protoc_insertion_point(field_add:Proto3Data.Vec1)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
Proto3Data::vec1() const {
  // @@protoc_insertion_point(field_list:Proto3Data.Vec1)
  return vec1_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
Proto3Data::mutable_vec1() {
  // @@protoc_insertion_point(field_mutable_list:Proto3Data.Vec1)
  return &vec1_;
}

// repeated uint64 Vec2 = 2;
inline int Proto3Data::vec2_size() const {
  return vec2_.size();
}
inline void Proto3Data::clear_vec2() {
  vec2_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Proto3Data::vec2(int index) const {
  // @@protoc_insertion_point(field_get:Proto3Data.Vec2)
  return vec2_.Get(index);
}
inline void Proto3Data::set_vec2(int index, ::PROTOBUF_NAMESPACE_ID::uint64 value) {
  vec2_.Set(index, value);
  // @@protoc_insertion_point(field_set:Proto3Data.Vec2)
}
inline void Proto3Data::add_vec2(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  vec2_.Add(value);
  // @@protoc_insertion_point(field_add:Proto3Data.Vec2)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >&
Proto3Data::vec2() const {
  // @@protoc_insertion_point(field_list:Proto3Data.Vec2)
  return vec2_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint64 >*
Proto3Data::mutable_vec2() {
  // @@protoc_insertion_point(field_mutable_list:Proto3Data.Vec2)
  return &vec2_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_vectors_2eproto
